# Generated by Django 3.1.5 on 2021-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('PublishDate', models.DateField()),
            ],
        ),
    ]
